spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DATABASE_URL}:3306/chats
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
      defer-datasource-initialization: true

    open-in-view: false


  rabbitmq:
    host: ${MQ_URL}
    port: 5672
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    template:
      retry:
        enabled: true
        initial-interval: "2s"

  thymeleaf:
    cache: false
  profiles:
    group:
      prod:
        - oauth

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret_key: ${JWT_SECRET}

